permalink: /:year/:month/:day/:title
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
paginate: 5
paginate_path: "news/page/:num"
excerpt_separator: "\n\n\n"

title : ConfuserEx-Reborn
description: ConfuserEx is an open-source protector for .NET applications.
repo : "https://github.com/CubeCoders/ConfuserEx-Reborn"
author:
  name: Ki
  email: contact@cubecoders.com

production_url : //cubecoders.github.io/ConfuserEx-Reborn

JB :
  version : 0.3.0
  BASE_PATH : //cubecoders.github.io/ConfuserEx-Reborn

  ASSET_PATH : false

  archive_path: /archive/
  atom_path : /atom.xml
  rss_path : /rss.xml
